### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by dazuling** [dazuling/ambience#1]
- [ ] lib
  - [x] library scanner
  - [x] tag reading
  - [x] database schema
  - [ ] scheduled scans
  - [x] virtual tags (m-tags)
  - [ ] tag writing
  - [x] configuration
  - [x] collections
    - [x] tracks
    - [x] albums
    - [x] artists
  - [ ] saved filters
    - [ ] artist
    - [ ] record label
    - [ ] genre
    - [ ] year range
  - [ ] cover art
    - [ ] cover art in directory
    - [ ] cover art in file tags
  - [ ] transcoding
- [x] cli
  - [x] configuration management
  - [x] daemon start/stop/status
  - [x] database creation/migration
  - [x] scanner trigger
  - [x] user management
  - [x] development tools
- [ ] api
  - [ ] config reload
  - [ ] api keys
    - [x] creation (login)
    - [ ] manual expiration
    - [ ] view api keys
  - [ ] user management
    - [ ] change password
  - [ ] file serving
    - [x] music files
    - [ ] covers
  - [ ] track fetching
    - [ ] fetch track data
    - [ ] album/artist/genre/year/record label filters
  - [ ] album fetching
    - [ ] fetch album data
    - [ ] artist/genre/year/record label filters
  - [ ] artist fetching
    - [ ] fetch artist data
    - [ ] genre/year/record label filters
  - [ ] collections
    - [ ] addition of tracks/artists/albums
    - [ ] removal of tracks/artists/albums
    - [ ] view tracks/artists/albums
  - [ ] filters
    - [ ] addition of filters
    - [ ] removal of filters
    - [ ] view filters
    - [ ] view tracks/artists/albums for filter
